# Poetry pre-commit hook 
# Source: https://github.com/pre-commit/pre-commit/issues/1414
# repos:
# - repo: local
#   hooks:
#   - id: update-requirements-txt
#     name: update-requirements-txt
#     description: 'Generate requirements.txt based on poetry.lock'
#     entry: poetry
#     args: [export, --format, requirements.txt, --output, requirements.txt]
#     language: system
#     pass_filenames: false

repos:
- repo: local
  hooks:
  - id: update-requirements-txt-in-ansible-setup
    name: update-requirements-txt-in-ansible-setup
    description: 'Generate requirements.txt based on poetry.lock'
    entry: bash -c 'cd setup-using-ansible && poetry export --without-hashes --format "requirements.txt" --output "requirements.txt"'
    language: system
    pass_filenames: false

- repo: local
  hooks:
  - id: update--dev-requirements-txt-in-ansible-setup
    name: update--dev-requirements-txt-in-ansible-setup
    description: 'Generate requirements-dev.txt based on poetry.lock'
    entry: bash -c 'cd setup-using-ansible && poetry export --dev --without-hashes --format "requirements.txt" --output "requirements-dev.txt"'
    language: system
    pass_filenames: false